### PR TITLE
Changed the way to hide the menu bar

### PR DESCRIPTION
**Pull request by wheredidhugo**

### CODE REVIEW

**Comment by lostdesign** [comment]
Thanks for your PR, I will check it out within this week. Sorry for the delay.

**Comment by bgpvp** [comment]
No problem!

**Comment by the94air** [comment]
:eye:

**Comment by lostdesign** [comment]
@bgpvp any idea since when this property is supported? This project still is on electron v9 :D

**Comment by bgpvp** [comment]
This has been supported since [Electron v8.3](https://github.com/electron/electron/blob/v8.3.0/docs/api/browser-window.md#new-browserwindowoptions). 
So this should be alright but I’m not sure since I haven’t tested it.

**Comment by bgpvp** [comment]
Small bump

**Comment by lostdesign** [comment]
Sorry for taking so long, this feature could have been merged early on. My current project https://github.com/lostdesign/linked is taking all my focus 😇

But, teamotes will get a signed version and some more love in the future.

**Pull request merged**
